### ISSUE TITLE
unable to login to admin page / unknown OTP

### ISSUE THREAD

**Issue by GeekAnnoyed** [YunoHost-Apps/snappymail_ynh#119]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

unable to login to admin page, it asks for the admin/password and OTP
using
 admin as username 
 the password in the file listed post install
 and leaving the OTP blank

I'm told "Authentication failed"

### Context

- Hardware: www.hetzner.com arm server
- YunoHost version: 11.2.4 (stable).
- I have access to my server: SSH and Web interface
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 

- Using, or trying to install package version/branch: stable
- If upgrading, current package version: 2.29.1~ynh1

### Steps to reproduce
login to
   1. *Go to  domain.com/snappymail/app/?admin
   2. *Fillout username and password using /var/www/snappymail/app/data/_data_/_default_/admin_password.txt
   3. *Click "login to admin panel
   4. Failure to login with "Authentication failed"

### Expected behavior

Not sure, as I have never seen it. but I would assume an admin interface.

### Logs
nothing of any worth in them

**Comment by stilobique** [comment]
Not possible to access the admin panel, this issue still present ?? (#10)

[Other error with this behavior](https://forum.yunohost.org/t/impossible-dacceder-a-ladministration-de-snappymail/26734).
Update the `admin.md` to give more information about this setup.

**Comment by nicoco973** [comment]
hello, 
did you find an issus ?

**Comment by GeekAnnoyed** [comment]
Hello, so sorry for the delay in replying, life happened.

I tried and still no joy. it just will not let me log in.

**Comment by GeekAnnoyed** [comment]
> I find this issue and this work well for me, the last message. #122

this sorted it, thank you so much :dancers:
