### ISSUE TITLE
login to admin page broken

### ISSUE THREAD

**Issue by chri2** [YunoHost-Apps/snappymail_ynh#122]
### Describe the bug

Can't access snappymail admin page.

### Context

- Hardware: RockPro64 + 2x sata ssd as software raid1
- YunoHost version: 11.2.5
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: **multiple domains for email, added aliases as described [here](https://forum.yunohost.org/t/add-a-redirection-mail-alias-without-attaching-it-to-a-yunohost-account/182)**
- Using, or trying to install package version/branch: SnappyMail 2.29.1~ynh1

### To reproduce

On my yunohost: 
* install SnappyMail (own subdomain snappymail.do.main, path '/')
* go to the admin url https://smail.do.main/app/?admin
* get password from `/var/www/snappymail/app/data/_data_/_default_/admin_password.txt`
* try to login using username `admin` and the password from above mentioned file

### Expected behavior

Access to snappymails web admin.

### Logs

from `/var/log/nginx/smail.do.main-error.log`:
```
2023/10/13 17:07:46 [error] 802501#802501: *1446 FastCGI sent in stderr: "PHP message: PHP Notice:  Invalid plugin class LdapIdentitiesPlugin in /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Plugins/Manager.php on line 147" while reading response header from upstream, client: 192.168.2.20, server: smail.do.main, request: "GET /app/?/AdminAppData/0/5370959716450588/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-snappymail.sock:", host: "smail.do.main"
```

Seems unrelated, because when I set `enabled_list = ""` in `/var/www/snappymail/app/data/_data_/_default_/configs/application.ini` the error vanishes, but still the login to the admin page is not possible.

* I tried to purge and re-install snappymail
* I tried to set the password in the application.ini (snappymail stops to generate new passwords, but the password doesn't work).

**Comment by chri2** [comment]
Debug log of snappymail:
```
[2023-10-13 19:38:40.641][52d4f8fb] [INFO]: [SM:2.29.1][IP:192.168.2.20][PID:808560][nginx/1.18.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://smail.link-goe.de/app/?admin/Json/&q[]=/0/]
[2023-10-13 19:38:40.645][52d4f8fb] PHP-USER[NOTICE]: Invalid plugin class LdapIdentitiesPlugin /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Plugins/Manager.php [line:147, code:1024]
[2023-10-13 19:38:40.648][52d4f8fb] [INFO]: [SM:2.29.1][IP:192.168.2.20][PID:808560][nginx/1.18.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://smail.link-goe.de/app/?admin/Json/&q[]=/0/]
[2023-10-13 19:38:40.652][52d4f8fb] JSON[INFO]: Action: DoAdminLogin
[2023-10-13 19:38:40.653][52d4f8fb] POST[INFO]: {"Login":"admin","Password":"*******","TOTP":"","Action":"AdminLogin"}
[2023-10-13 19:38:45.615][52d4f8fb] SERVICE[WARNING]: AuthError[102]
#0 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\ActionsAdmin->DoAdminLogin()
#1 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/snappymail/app/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#4 /var/www/snappymail/app/index.php(11): include('...')
#5 {main}
[2023-10-13 19:38:45.615][52d4f8fb] [NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/ActionsAdmin.php:124
Stack trace:
#0 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\ActionsAdmin->DoAdminLogin()
#1 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/snappymail/app/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/snappymail/app/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#4 /var/www/snappymail/app/index.php(11): include('...')
#5 {main}
[2023-10-13 19:38:45.616][52d4f8fb] JSON[INFO]: {"Action":"AdminLogin","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1697218725}
[2023-10-13 19:38:45.619][52d4f8fb] [INFO]: Last error: {"type":1024,"message":"Invalid plugin class LdapIdentitiesPlugin","file":"\/var\/www\/snappymail\/app\/snappymail\/v\/2.29.1\/app\/libraries\/RainLoop\/Plugins\/Manager.php","line":147}
[2023-10-13 19:38:45.620][52d4f8fb] [INFO]: Memory peak usage: 2MB
[2023-10-13 19:38:45.620][52d4f8fb] [INFO]: Time delta: 5.0057051181793
```

Related to https://github.com/the-djmaze/snappymail/issues/1283 ?

**Comment by chri2** [comment]
I ended up getting a older version of `application.ini` from my backup and changed lines containing the admin account and password back to their latest known to work content.

This did it.

It seems that the **initial password** doesn't work. Put a known to work password hash into `application.ini` and it should work.

Why the initial password do not work anymore I didn't find out.

A side notice is that the following happened between 2023-09-26 and now:

```
 [version]
-current = "2.28.4"
-saved = "Fri, 08 Sep 2023 10:15:40 +0000"
\ Kein Zeilenumbruch am Dateiende.
+current = "2.28.1"
+saved = "Wed, 21 Jun 2023 06:38:05 +0000"
```

It seems that for some reason at least my snappymail has been downgraded. Maybe this introduced the problems with the initial password.

**Comment by chri2** [comment]
There is [this issue](https://github.com/the-djmaze/snappymail/discussions/1133) describing how to hash a password - didn't try it, yet. The method might be usable to set a password manually in `application.ini`.

If you're desperate you can set the password `secret` by using `admin_password = "$2y$10$1WLBpaFTbSrh.j6mY5D6hefBdqSFD5prxgTbUu0f7LOFHfCCNdbma"` in your application.ini and changing it immediately afterwards via the admin webinterface.

**Comment by nicoco973** [comment]
Hello, 
I have the same problem. 
I did'nt log me with my admin password and i retry install snappymail. It's the same.. 
Did you have a good way to fix it ? 
i try your last message but this dont work for me.

**Comment by chri2** [comment]
Uhm, the admin password might be salted with some (hopefully) unique value stored somewhere. I'm not that deep into snappymail, to tell exactly, but that would at least be an explanation.

**Comment by chri2** [comment]
I look some further and found the following: after snappymail installation the configuration file is set to file mode 0400 (read only):

```
root@yt:~# ls -l /var/www/snappymail/app/data/_data_/_default_/configs/application.ini 
-r-------- 1 snappymail snappymail 9385 Oct 30 11:19 /var/www/snappymail/app/data/_data_/_default_/configs/application.ini
```

If I set the file to 0600 (read-write), delete the generated admin password to get a new one like this …
```
root@yt:~# chmod 600 /var/www/snappymail/app/data/_data_/_default_/configs/application.ini
root@yt:~# rm /var/www/snappymail/app/data/_data_/_default_/admin_password.txt
```
…then **open or reload the admin webpage** to get a new `admin_password.txt` I can log in afterwards with the new password from that file.

**Comment by nicoco973** [comment]
this issue work's very well. Thx so much.

**Comment by chri2** [comment]
https://github.com/YunoHost-Apps/snappymail_ynh/pull/126

**Comment by tomdereub** [comment]
Hi, I don't know if it's the same issue or not, but I can't access admin page too. When I want to access https://mail.plaf.fr//app/?admin, I have to first login on SSO, then I get this screen (just after a fresh install) : 
![image](https://github.com/YunoHost-Apps/snappymail_ynh/assets/16243499/4a6fc965-1c52-4912-b023-cbd715c79f04)

The rights of /var/www/snappymail/app/data/_data_/_default_/configs/application.ini are already read-write : 
```
ls -l /var/www/snappymail/app/data/_data_/_default_/configs/application.ini
-rw------- 1 snappymail snappymail 9308  8 déc.  12:26 /var/www/snappymail/app/data/_data_/_default_/configs/application.ini
```
But I have no admin_password.txt file.
Any idea ? I can give some logs if necessary.

**Comment by rujash7** [comment]
I had this issue on a new install VPS. This app isn't as stable as the diamond/star let on.
