### ISSUE TITLE
Upgrade to version 2.37.1 fails

### ISSUE THREAD

**Issue by PraetorIM** [YunoHost-Apps/snappymail_ynh#175]
Upgrade to version 2.37.1 fails; the download link for snappymail from Github leads to a 404 message.

This is probably due to the fact that 2.37.2 has been published in the meantime and only this newer version is available for download.

**Comment by rmueck** [comment]
Same issue here!

**Comment by PraetorIM** [comment]
See [Pull Request #176](https://github.com/YunoHost-Apps/snappymail_ynh/pull/176)

**Comment by Salamandar** [comment]
Fixed now. Github decides to delete artifacts with no reason…
