### ISSUE TITLE
Admin access with [202] mkdir() failed error since 2.38.2~ynh1

### ISSUE THREAD

**Issue by Quiwy** [YunoHost-Apps/snappymail_ynh#186]
### Admin access with [202] mkdir() failed error since 2.38.2~ynh1 (upgrade from 2.37.3\~ynh1)

When accessing admin url, I have the following error since last update.
```
[202] mkdir() failed
```

### Context

- Hardware: Other ARM board
- YunoHost version: 11.2.31

### Expected behavior
Access to snapymail admin.

I guess it's related to some of these changes : https://github.com/YunoHost-Apps/snappymail_ynh/pull/180/files#diff-57aeb84da86cb7420dfedd8e49bc644fb799d5413d01927a0417bde753e8922f

For now, to gained admin access back, I did `chown -R "snappymail:www-data" app/`

**Comment by Tagadda** [comment]
Confirmed, fixed too with `chown -R snappymail:www-data /var/www/snappymail/app`

**Comment by Tagadda** [comment]
Is this still happening ?
