### ISSUE TITLE
SSO is broken

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/snappymail_ynh#187]
### Describe the bug

When logged in with YunoHost, you shouldn't be asked to log in SnappyMail.

### Context

- YunoHost version: 12.0.6

### Steps to reproduce

- Login to YunoHost portal
- Click on SnappyMail

### Expected behavior

https://github.com/YunoHost-Apps/snappymail_ynh/blob/master/conf/sso.php should log you in snappymail using YunoHost HTTP headers or something
This might be related to YunoHost 12 ssowat changes.

**Comment by gnouts** [comment]
I've just upgraded to yunohost v12 and made a fresh install of snappymail. This seems to still be an issue on my end. I mean I still have to enter my email and password on the snappymail login screen, while already being logged in SSOwat.

In the debug console, I see the request containing 'sso=&hash=xyz'. The response is 302 cached and I get an html saying javascript is needed. Using latest firefox with ublock and firefox shield deactivated. 
What am I missing ?
