### ISSUE TITLE
Enable SSO

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/snappymail_ynh#19]
We could get inspiration from the Rainloop package : https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/sso/sso.php

**Comment by youplaboum** [comment]
It would be a great addition, it's one of the very few things I miss after migrating from roundcube to snappymail

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/issues/321#issuecomment-1179514736

**Comment by sideeffectdk** [comment]
This would be an amazing addition to this package.
I've found snappymail to be just the thing for my non-profit volunteer driven venue. Having SSO would make the less tech-savvy board members that needs to access mail, shriek out in joy.

**Comment by the-djmaze** [comment]
@sideeffectdk SSO works, but you need to write the additional code for your specific environment.
