### ISSUE TITLE
Access denied on MySQL for Carddav sync

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/snappymail_ynh#4]
Hello,

I installed SnappyMail 2.15.0~ynh2 on YunoHost 4.3.6.3 (stable)

When I go to Admin page then on Contacts section, I test the Stockage (PDO) with the "Test" button, and I have in return 
![image](https://user-images.githubusercontent.com/18677287/165523090-817dc5b7-976f-4d08-8a9e-78b7525140ab.png)

Should I modify something for the database to be accessed and the Contact Sync works?

Thanks in advance for your suggestion

**Comment by ericgaspar** [comment]
By default SnappyMail is using SQLite as database which is enough for most users... The package doesn't creat a MySQL database.

There is a branch where you can choose the database to be used (SQLite/MySQL): `https://github.com/YunoHost-Apps/snappymail_ynh/tree/mysql`

**Comment by croulibri** [comment]
But is there a way to use SQLite for contact synchronisation also?
There is a drop-down menu on this Contacts section / Stockage (PDO) , but I can't chose SQLite.

PS: a big thanks for your work to package this webmail 🙂

**Comment by ericgaspar** [comment]
You maybe missing php-sqlite3 librarie...

Can you try:

```
sudo apt install php7.4-sqlite3
```

**Comment by croulibri** [comment]
Yes, this was the missing package 🙂 
Carddav Sync is working now with SQLite!

A big thanks to you 🤗
