### ISSUE TITLE
upgrade to 2.18.4 breaks multi accounts

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/snappymail_ynh#47]
### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.9.15
- I have access to my server: *Through SSH*

### Steps to reproduce

After upgrading to 2.18.4, I noticed this:

when logging into my main account, I could still use the other accounts attached to the main one, the problem is if I switch to an other account, I can't go back to my main account, which is "blanked" (nothing written on the line). I've switched back to the previous version which was working.

I've installed snappymail on another yunohost instance, and I have the same behavior:

![image](https://user-images.githubusercontent.com/477243/194550621-f5193baa-0c4a-4bf1-8b0d-12c3c106a533.png)

(you can see the blank account there)

**Comment by farvardin** [comment]
(I can't tell if it's a yunohost error or an upstream problem)

**Comment by ericgaspar** [comment]
[2.18.5](https://github.com/the-djmaze/snappymail/releases/tag/v2.18.5) is out and should solve the issue. (I guess). You can try from the testing branch.

**Comment by farvardin** [comment]
ah oui : "Top email address not showing in drop down menu https://github.com/the-djmaze/snappymail/issues/543"

j'essaye ça à l'occasion, merci
