### ISSUE TITLE
Package conflict

### ISSUE THREAD

**Issue by NoWiS-** [YunoHost-Apps/snappymail_ynh#8]
Hi,

I tried to install it as a replacement from rainloop, however i ran into a package conflict, it looks like an issue with nextcloud.
Full report here:
https://paste.yunohost.org/raw/siwivupuwa

**Comment by OniriCorpe** [comment]
Oy

I have exactly the same problem

**Comment by Tagadda** [comment]
Just installed Snappymail alongside Rainloop without any issues.
https://paste.yunohost.org/raw/ajazikosas

**Comment by LukeOssevoort** [comment]
Encountering similar issues upgrading on an RPi4 https://paste.yunohost.org/raw/iwuhojafok
I believe it is an issue with the script for the dependencies.

**Comment by OniriCorpe** [comment]
It seems fixed, today I was able to install correctly (with nextcloud installed)

@NoWiS- @LukeOssevoort  can you test?

**Comment by ericgaspar** [comment]
closing. Please reopen if this is still an issue.
