### ISSUE TITLE
Last update broke snappymail

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/snappymail_ynh#92]
## My YunoHost server

Yunohost 11.1.5.4 (stable)
VPS Hetzner CX 31 (8Go RAM 2 vCPU intel)
Interface admin + SSH

I tried to update from 2.25.1 to 2.25.4 but it failed. Now, i cannot open the app configuration's panel in admin's interface and it looks like the app is disappeared.

Here is logs : https://paste.yunohost.org/raw/idojilizuv

**Comment by mrtpcet** [comment]
And i'm unable to restore de pre-update backup : https://paste.yunohost.org/raw/qumoxadoce

**Comment by ericgaspar** [comment]
ah yes, Snappymail is using the new package app v2 version... Some of the issues are resolved by updating YunoHost to version 11.1.6

**Comment by mrtpcet** [comment]
That's worked ! Thanks
