### ISSUE TITLE
Failed update: useradd command failed with exit code 2304

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/snappymail_ynh#97]
### Describe the bug

I would like to update Snappymail package but it fails.

Error says: "_Failed to update system_user : useradd command failed with exit code 2304_"

### Context

Server on dedicated server Kimsufi KS1
yunohost_version: 11.1.7
CURRENT SNAPPYMAIL VERSION: 2.25.1
DESIRED SNAPPYMAIL VERSION: 2.26.1

### Steps to reproduce

Try to update Snappymail through web-interface or SSH.

### Expected behavior

Snappymail is updated :-)

### Logs

https://paste.yunohost.org/raw/ibilugoceh

**Comment by alexAubin** [comment]
Hmmmokay, can you share the output of `grep snappymail /etc/passwd`

Also could it be that you created a YunoHost called "Snappymail" at some point ? (NB : I mean a YunoHost user, not a unix user)

**Comment by croulibri** [comment]
Bonjour @alexAubin 
The command gave `snappymail:x:984:984::/var/www/snappymail:/usr/sbin/nologin`

I have not created any user, except "real" users of my server (but no user for apps).

**Comment by alexAubin** [comment]
Ah indeed, nevermind, I'm looking at YunoHost's code and it indeed sounds like there's a big issue with the code supposed to check wether or not the user exists :sweat_smile:

**Comment by croulibri** [comment]
Aaaah, I understand your question now!
No no, none of my user is called Snappymail ;-)

**Comment by alexAubin** [comment]
So I pushed this fix to be made available in the next minor iteration : https://github.com/YunoHost/yunohost/commit/d123fd7674a936648f6117bcfd0ec538e775bc62

**Comment by croulibri** [comment]
Thanks you @alexAubin 
There is no rush from my side as Snappymail still works.
I understand next update of Snappymail should work.

Have I made something incorrect to get this error?

**Comment by ericgaspar** [comment]
No, the package has been updated with package version 2, so there are little things here and there...

**Comment by croulibri** [comment]
The last update of Yunohost core and/or of Snappymail solve this issue.
Thanks to both of you 🤗
