### ISSUE TITLE
snappymail doesn't send emails

### ISSUE THREAD

**Issue by lucyferu** [YunoHost-Apps/snappymail_ynh#99]
### Describe the bug

*when i try to send an email with snappymail, it loads for a bit and then an error message announces “Can’t send email”.*

### Context

- Hardware: *VPS bought online (Contabo)*
- YunoHost version: 11.1.9 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 2.26.2~ynh1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to snappymail*
   2. *Compose a new email*
   3. *Click send*
   4. *See error*

### Expected behavior

*just being able to send and email*

### Logs

i don't have a yunohost log, but i can share services logs if useful? if so, which one? dovecot? postfix? others?

Find the error screenshot [here](https://postimg.cc/FkXkn843).

**Comment by Jaxom99** [comment]
I have the same trouble, I just tried upgrading to last version but no luck. The app asked me to set "default folders" for Spam, archive, etc. But after that, nothing changed and the message is still not sent.

The only sensible log line I get is from mail.info :
 `Feb 27 21:15:33 yuno postfix/smtpd[1655576]: NOQUEUE: reject: RCPT from localhost[::1]: 553 5.7.1 <user@specific-ynh-domain.tld>: Sender address rejected: not logged in; from=<user@domain.tld> to=<external@external.tld> proto=ESMTP helo=<main-yuno-domain.tld>`

**Comment by spooknik** [comment]
I am also having this same issue. Anyone have any suggestions? I get the following in mail.info

` NOQUEUE: reject: RCPT from localhost.localdomain[127.0.0.1]: 553 5.7.1 <myemail@mydomain.com>: Sender address rejected: not logged in; from=<myemail@mydomain.com> to=<person@domain.com> proto=ESMTP helo=<mydomain.com>`

**Comment by axemann** [comment]
Same issue here too.  The post-install instructions say to retrieve the admin password from `/var/www/snappymail/data/_data_/_default_/admin_password.txt`, but that file does not exist, even on a new install:

![image](https://user-images.githubusercontent.com/17078534/236718206-ea8ab76c-fc76-46a0-b7c5-cf6aeca84843.png)

**Comment by Jaxom99** [comment]
Thank you @stilobique for the details. Maybe we could put your comments somewhere in the install process, to make it visible from ynh' admins ? 

By the way, I see no post-install instructions in the admin panel. Are they displayed here, or is it just a web link to documentation ? (if so, we could make it more obvious...)

**Comment by stilobique** [comment]
There are's some improvement todo with the install setup. I don't know how make that, i wish try to package and write any PR to improve the post-install.

**Comment by ericgaspar** [comment]
Use `ADMIN.md` (https://github.com/YunoHost-Apps/snappymail_ynh/blob/testing/doc/ADMIN.md) to add relevant info about how to set Snappymail, or you can copy instructions here so I can add them.

**Comment by alexAubin** [comment]
Tip added in ADMIN.md in https://github.com/YunoHost-Apps/snappymail_ynh/pull/107

Assuming this is fixed ... though ideally this kind of stuff should be automagically configured by YunoHost
